stages:
  - test
  - build

test:
  image: node:10.15-alpine
  stage: test
  variables:
    DB_HOST: "mongo"
    DB_PORT: "27017"
    DB_DATABASE: "streamers-edge-test"
  services:
    - mongo
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules
  script:
    - apk --update-cache add make gcc g++ python git
    - npm config set unsafe-perm true
    - npm i
    - npm run test:audit
    - npm run test:lint
    - npm run test:mocha
  tags:
    - docker
  only:
    - merge_requests
    - develop
    - master
