#!/usr/bin/env bash

# Exit the script as soon as something fails.
set -e

# Where is our config located?
DEFAULT_CONFIG_PATH="/streamersedge/config/default.json"
PRODUCTION_CONFIG_PATH="/streamersedge/config/production.json"
DEVELOPMENT_CONFIG_PATH="/streamersedge/config/development.json"

# Replace all instances of the placeholders with the values above.


## Default

sed -i "s|DB_USER|$DB_USER|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|DB_PASSWORD|$DB_PASSWORD|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|DB_HOST|$DB_HOST|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|DB_PORT|$DB_PORT|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|DB_DATABASE|$DB_DATABASE|g" "${DEFAULT_CONFIG_PATH}"

sed -i "s|TWITCH_ID|$TWITCH_ID|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|TWITCH_SECRET|$TWITCH_SECRET|g" "${DEFAULT_CONFIG_PATH}"

sed -i "s|GOOGLE_ID|$GOOGLE_ID|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|GOOGLE_SECRET|$GOOGLE_SECRET|g" "${DEFAULT_CONFIG_PATH}"

sed -i "s|FACEBOOK_ID|$FACEBOOK_ID|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|FACEBOOK_SECRET|$FACEBOOK_SECRET|g" "${DEFAULT_CONFIG_PATH}"

sed -i "s|BACKEND_URL|$BACKEND_URL|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|FRONTEND_URL|$FRONTEND_URL|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|FRONTEND_CALLBACK_URL|$FRONTEND_CALLBACK_URL|g" "${DEFAULT_CONFIG_PATH}"

sed -i "s|MAILER_HOST|$MAILER_HOST|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|MAILER_USER|$MAILER_USER|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|MAILER_PASS|$MAILER_PASS|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|MAILER_SENDER|$MAILER_SENDER|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|MAILER_PORT|$MAILER_PORT|g" "${DEFAULT_CONFIG_PATH}"


sed -i "s|PEERPLAYS_WS|$PEERPLAYS_WS|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_FAUCET_URL|$PEERPLAYS_FAUCET_URL|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_REFERRER|$PEERPLAYS_REFERRER|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_SEND_ASSET_ID|$PEERPLAYS_SEND_ASSET_ID|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_PAYMENT_ACCOUNT_ID|$PEERPLAYS_PAYMENT_ACCOUNT_ID|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_PAYMENT_ACCOUNT_WIF|$PEERPLAYS_PAYMENT_ACCOUNT_WIF|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_PAYMENT_RECEIVER_ID|$PEERPLAYS_PAYMENT_RECEIVER_ID|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_FEE_RECEIVER|$PEERPLAYS_FEE_RECEIVER|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_PAYMENT_RECEIVER_WIF|$PEERPLAYS_PAYMENT_RECEIVER_WIF|g" "${DEFAULT_CONFIG_PATH}"

sed -i "s|PAYPAL_ID|$PAYPAL_ID|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PAYPAL_SECRET|$PAYPAL_SECRET|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PAYPAL_ENVIRONMENT|$PAYPAL_ENVIRONMENT|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PAYPAL_OPENID_SCOPES|$PAYPAL_OPENID_SCOPES|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PAYPAL_PAYOUTS_EMAIL_SUBJECT|$PAYPAL_PAYOUTS_EMAIL_SUBJECT|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|PAYPAL_PAYOUTS_EMAIL_MESSAGE|$PAYPAL_PAYOUTS_EMAIL_MESSAGE|g" "${DEFAULT_CONFIG_PATH}"

sed -i "s|COINMARKETCAP_KEY|$COINMARKETCAP_KEY|g" "${DEFAULT_CONFIG_PATH}"

sed -i "s|VAPID_PUBLIC|$VAPID_PUBLIC|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|VAPID_PRIVATE|$VAPID_PRIVATE|g" "${DEFAULT_CONFIG_PATH}"

sed -i "s|SE_SERVICE_EMAIL|$SE_SERVICE_EMAIL|g" "${DEFAULT_CONFIG_PATH}"

sed -i "s|S3_BUCKET|$S3_BUCKET|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|CDN_URL|$CDN_URL|g" "${DEFAULT_CONFIG_PATH}"

sed -i "s|PUBG_KEY|$PUBG_KEY|g" "${DEFAULT_CONFIG_PATH}"

sed -i "s|CHALLENGE_JOIN_FEE|$CHALLENGE_JOIN_FEE|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|CHALLENGE_USER_REWARD_PERCENT|$CHALLENGE_USER_REWARD_PERCENT|g" "${DEFAULT_CONFIG_PATH}"
sed -i "s|CHALLENGE_USER_REDEEM_PERCENT|$CHALLENGE_USER_REDEEM_PERCENT|g" "${DEFAULT_CONFIG_PATH}"


## Production

sed -i "s|BACKEND_URL|$BACKEND_URL|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|FRONTEND_URL|$FRONTEND_URL|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|FRONTEND_CALLBACK_URL|$FRONTEND_CALLBACK_URL|g" "${PRODUCTION_CONFIG_PATH}"

sed -i "s|PUBG_KEY|$PUBG_KEY|g" "${PRODUCTION_CONFIG_PATH}"

sed -i "s|PEERPLAYS_WS|$PEERPLAYS_WS|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|PEERPLAYS_FAUCET_URL|$PEERPLAYS_FAUCET_URL|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|PEERPLAYS_REFERRER|$PEERPLAYS_REFERRER|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|PEERPLAYS_SEND_ASSET_ID|$PEERPLAYS_SEND_ASSET_ID|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|PEERPLAYS_PAYMENT_ACCOUNT_ID|$PEERPLAYS_PAYMENT_ACCOUNT_ID|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|PEERPLAYS_PAYMENT_ACCOUNT_WIF|$PEERPLAYS_PAYMENT_ACCOUNT_WIF|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|PEERPLAYS_PAYMENT_RECEIVER_ID|$PEERPLAYS_PAYMENT_RECEIVER_ID|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|PEERPLAYS_FEE_RECEIVER|$PEERPLAYS_FEE_RECEIVER|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|PEERPLAYS_PAYMENT_RECEIVER_WIF|$PEERPLAYS_PAYMENT_RECEIVER_WIF|g" "${PRODUCTION_CONFIG_PATH}"

sed -i "s|PAYPAL_ID|$PAYPAL_ID|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|PAYPAL_SECRET|$PAYPAL_SECRET|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|PAYPAL_ENVIRONMENT|$PAYPAL_ENVIRONMENT|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|PAYPAL_OPENID_SCOPES|$PAYPAL_OPENID_SCOPES|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|PAYPAL_PAYOUTS_EMAIL_SUBJECT|$PAYPAL_PAYOUTS_EMAIL_SUBJECT|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|PAYPAL_PAYOUTS_EMAIL_MESSAGE|$PAYPAL_PAYOUTS_EMAIL_MESSAGE|g" "${PRODUCTION_CONFIG_PATH}"

sed -i "s|COINMARKETCAP_KEY|$COINMARKETCAP_KEY|g" "${PRODUCTION_CONFIG_PATH}"

sed -i "s|VAPID_PUBLIC|$VAPID_PUBLIC|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|VAPID_PRIVATE|$VAPID_PRIVATE|g" "${PRODUCTION_CONFIG_PATH}"

sed -i "s|TWITCH_ID|$TWITCH_ID|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|TWITCH_SECRET|$TWITCH_SECRET|g" "${PRODUCTION_CONFIG_PATH}"

sed -i "s|GOOGLE_ID|$GOOGLE_ID|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|GOOGLE_SECRET|$GOOGLE_SECRET|g" "${PRODUCTION_CONFIG_PATH}"

sed -i "s|FACEBOOK_ID|$FACEBOOK_ID|g" "${PRODUCTION_CONFIG_PATH}"
sed -i "s|FACEBOOK_SECRET|$FACEBOOK_SECRET|g" "${PRODUCTION_CONFIG_PATH}"

sed -i "s|DB_DATABASE|$DB_DATABASE|g" "${PRODUCTION_CONFIG_PATH}"

sed -i "s|S3_BUCKET|$S3_BUCKET|g" "${PRODUCTION_CONFIG_PATH}"


## Development

sed -i "s|BACKEND_URL|$BACKEND_URL|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|FRONTEND_URL|$FRONTEND_URL|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|FRONTEND_CALLBACK_URL|$FRONTEND_CALLBACK_URL|g" "${DEVELOPMENT_CONFIG_PATH}"

sed -i "s|PUBG_KEY|$PUBG_KEY|g" "${DEVELOPMENT_CONFIG_PATH}"

sed -i "s|PEERPLAYS_WS|$PEERPLAYS_WS|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_FAUCET_URL|$PEERPLAYS_FAUCET_URL|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_REFERRER|$PEERPLAYS_REFERRER|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_SEND_ASSET_ID|$PEERPLAYS_SEND_ASSET_ID|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_PAYMENT_ACCOUNT_ID|$PEERPLAYS_PAYMENT_ACCOUNT_ID|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_PAYMENT_ACCOUNT_WIF|$PEERPLAYS_PAYMENT_ACCOUNT_WIF|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_FEE_RECEIVER_ID|$PEERPLAYS_FEE_RECEIVER_ID|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_FEE_RECEIVER|$PEERPLAYS_FEE_RECEIVER|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_PAYMENT_RECEIVER_WIF|$PEERPLAYS_PAYMENT_RECEIVER_WIF|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|PEERPLAYS_PAYMENT_RECEIVER_ID|$PEERPLAYS_PAYMENT_RECEIVER_ID|g" "${DEVELOPMENT_CONFIG_PATH}"

sed -i "s|PAYPAL_ID|$PAYPAL_ID|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|PAYPAL_SECRET|$PAYPAL_SECRET|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|PAYPAL_ENVIRONMENT|$PAYPAL_ENVIRONMENT|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|PAYPAL_OPENID_SCOPES|$PAYPAL_OPENID_SCOPES|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|PAYPAL_PAYOUTS_EMAIL_SUBJECT|$PAYPAL_PAYOUTS_EMAIL_SUBJECT|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|PAYPAL_PAYOUTS_EMAIL_MESSAGE|$PAYPAL_PAYOUTS_EMAIL_MESSAGE|g" "${DEVELOPMENT_CONFIG_PATH}"

sed -i "s|COINMARKETCAP_KEY|$COINMARKETCAP_KEY|g" "${DEVELOPMENT_CONFIG_PATH}"

sed -i "s|VAPID_PUBLIC|$VAPID_PUBLIC|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|VAPID_PRIVATE|$VAPID_PRIVATE|g" "${DEVELOPMENT_CONFIG_PATH}"

sed -i "s|TWITCH_ID|$TWITCH_ID|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|TWITCH_SECRET|$TWITCH_SECRET|g" "${DEVELOPMENT_CONFIG_PATH}"

sed -i "s|GOOGLE_ID|$GOOGLE_ID|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|GOOGLE_SECRET|$GOOGLE_SECRET|g" "${DEVELOPMENT_CONFIG_PATH}"

sed -i "s|FACEBOOK_ID|$FACEBOOK_ID|g" "${DEVELOPMENT_CONFIG_PATH}"
sed -i "s|FACEBOOK_SECRET|$FACEBOOK_SECRET|g" "${DEVELOPMENT_CONFIG_PATH}"

sed -i "s|DB_DATABASE|$DB_DATABASE|g" "${DEVELOPMENT_CONFIG_PATH}"

sed -i "s|S3_BUCKET|$S3_BUCKET|g" "${DEVELOPMENT_CONFIG_PATH}"


exec "$@"
