version: '3'

services:

  # 1
  postgres:
    image: postgres:latest
    container_name: "streamersedge.postgres"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=streamers-edge
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - 127.0.0.1:5432:5432


  # 2
  backend.api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "--", "npm", "run", "start"]
    environment:
      - MODULE=api
      - NODE_ENV=production
      - DB_PASSWORD=$POSTGRES_PASSWORD
    env_file:
      - .env
    container_name: "streamersedge.backend.api"
    ports:
      - 16761:3000
    restart: always
    depends_on:
      - postgres

volumes:
  postgres:
