version: "3.7"
services:
  db:
    image: postgres:11.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=streamersedge
    volumes:
      - "/var/docker_volumes/streamersedge:/var/lib/postgresql/data"
